test: common template rollout changes

diff --git a/.github/workflows/build-test-release.yml b/.github/workflows/build-test-release.yml
--- a/.github/workflows/build-test-release.yml
+++ b/.github/workflows/build-test-release.yml
@@ -170,14 +170,9 @@ jobs:
           path: snyk-scan_requirements.sarif
   build:
     name: build
-    needs:
-      - review_secrets
-      - snyk
-      #- semgrep
-      #- lint
-      #- compliance-copyrights
-      - compliance-dependencies
     runs-on: ubuntu-latest
+    needs:
+      - compliance-dependencies
     outputs:
       buildname: ${{ steps.buildupload.outputs.name }}
     steps:
@@ -627,7 +622,7 @@ jobs:
           then
             WORKFLOW_NAME=`argo resubmit -v -o json -n workflows ${{ steps.run-tests.outputs.workflow-name }} | jq -r .metadata.name`
             echo "::set-output name=workflow-name::$(echo $WORKFLOW_NAME)"
-            argo logs --follow ${WORKFLOW_NAME} -n workflows
+            argo logs --follow ${WORKFLOW_NAME} -n workflows || echo "... there was an error fetching logs, the workflow is still in progress. please wait for the workflow to complete ..."
           else
             echo "No retry required"
             argo wait ${{ steps.run-tests.outputs.workflow-name }} -n workflows
@@ -778,7 +773,7 @@ jobs:
           then
             WORKFLOW_NAME=`argo resubmit -v -o json -n workflows ${{ steps.run-tests.outputs.workflow-name }} | jq -r .metadata.name`
             echo "::set-output name=workflow-name::$(echo $WORKFLOW_NAME)"
-            argo logs --follow ${WORKFLOW_NAME} -n workflows
+            argo logs --follow ${WORKFLOW_NAME} -n workflows || echo "... there was an error fetching logs, the workflow is still in progress. please wait for the workflow to complete ..."
           else
             echo "No retry required"
             argo wait ${{ steps.run-tests.outputs.workflow-name }} -n workflows
@@ -852,7 +847,7 @@ jobs:
       fail-fast: false
       matrix:
         splunk: ${{ fromJson(needs.meta.outputs.matrix_supportedSplunk) }}
-        browser: ["chrome", "firefox", "safari"]
+        browser: ["chrome"]
     container:
       image: ghcr.io/splunk/workflow-engine-base:2.0.3
     env:
@@ -929,7 +924,7 @@ jobs:
           then
             WORKFLOW_NAME=`argo resubmit -v -o json -n workflows ${{ steps.run-tests.outputs.workflow-name }} | jq -r .metadata.name`
             echo "::set-output name=workflow-name::$(echo $WORKFLOW_NAME)"
-            argo logs --follow ${WORKFLOW_NAME} -n workflows
+            argo logs --follow ${WORKFLOW_NAME} -n workflows || echo "... there was an error fetching logs, the workflow is still in progress. please wait for the workflow to complete ..."
           else
             echo "No retry required"
             argo wait ${{ steps.run-tests.outputs.workflow-name }} -n workflows
@@ -1080,7 +1075,7 @@ jobs:
           then
             WORKFLOW_NAME=`argo resubmit -v -o json -n workflows ${{ steps.run-tests.outputs.workflow-name }} | jq -r .metadata.name`
             echo "::set-output name=workflow-name::$(echo $WORKFLOW_NAME)"
-            argo logs --follow ${WORKFLOW_NAME} -n workflows
+            argo logs --follow ${WORKFLOW_NAME} -n workflows || echo "... there was an error fetching logs, the workflow is still in progress. please wait for the workflow to complete ..."
           else
             echo "No retry required"
             argo wait ${{ steps.run-tests.outputs.workflow-name }} -n workflows
@@ -1173,12 +1168,14 @@ jobs:
         shell: bash
         run: |
           RUN_PUBLISH=`echo $NEEDS | jq ".[] |  select(  ( .result != \"skipped\" ) and .result != \"success\" ) | length == 0"`
-          if [[ $RUN_PUBLISH != 'false' ]]
+          if [[ $RUN_PUBLISH != *'false'* ]]
           then
               echo "::set-output name=run-publish::true"
+          else
+              echo "::set-output name=run-publish::false"
           fi
       - name: exit without publish
-        if: ${{ steps.check.outputs.run-publish != 'true' }}
+        if: ${{ steps.check.outputs.run-publish == 'false' || github.event_name == 'pull_request'}}
         run: |
           echo " some test job failed. "
           exit 1
